baseurl = "https://re-terminal.nebrowser.com"
languageCode = "en-us"
# theme = "hugo-theme-re-terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "blue"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true
  [params.banner]
    dismissible = false
    text = "Check it out on GitHub"
    url = "https://github.com/mirus-ua/hugo-theme-re-terminal"

[languages]
  [languages.en.params]
    title = "re-Terminal"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "re-Terminal"
      logoHomeLink = "/"

[languages.en.menu]
  [[languages.en.menu.main]]
    identifier = "submenu"
    name = "Sub menus"
    weight = 10
  [[languages.en.menu.main]]
    identifier = "subabout"
    name = "About"
    url = "/about"
    parent = "submenu"
  [[languages.en.menu.main]]
    identifier = "subshowcase"
    name = "Showcase"
    url = "/showcase"
    parent = "submenu"
  [[languages.en.menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
  [[languages.en.menu.main]]
    identifier = "showcase"
    name = "Showcase"
    url = "/showcase"


# Only for demo deploy perpous
[module]
  [[module.mounts]]
    source = 'demoSite/content'
    target = 'content'
  [[module.mounts]]
    source = 'demoSite/static'
    target = 'static'
  [[module.mounts]]
    source = 'static'
    target = 'static'
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'demoSite/layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'archetypes'
    target = 'archetypes'
